package model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 04 17:53:37 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxsshrJmrFormEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        JmrFormId,
        JmrFormNo,
        PersonId,
        BusinessUnitId,
        TransactionDate,
        Nominator,
        EmployeeName,
        Cadre,
        Position,
        DepartmentName,
        LineManager,
        ApprovalStatus,
        MobilityDepartment,
        MobilityDeptManager,
        MobilityType,
        Duration,
        ProposedStartDate,
        ProposedEndDate,
        LearningExpectations,
        ImpactOnJob,
        Comments,
        NextApprover,
        ApproverComments,
        PreviousApprover,
        PayrollBatchName,
        SoaFlowid,
        ErrorMsg,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        DeptManagerEmailAddr;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int JMRFORMID = AttributesEnum.JmrFormId.index();
    public static final int JMRFORMNO = AttributesEnum.JmrFormNo.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int NOMINATOR = AttributesEnum.Nominator.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int CADRE = AttributesEnum.Cadre.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int LINEMANAGER = AttributesEnum.LineManager.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int MOBILITYDEPARTMENT = AttributesEnum.MobilityDepartment.index();
    public static final int MOBILITYDEPTMANAGER = AttributesEnum.MobilityDeptManager.index();
    public static final int MOBILITYTYPE = AttributesEnum.MobilityType.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int PROPOSEDSTARTDATE = AttributesEnum.ProposedStartDate.index();
    public static final int PROPOSEDENDDATE = AttributesEnum.ProposedEndDate.index();
    public static final int LEARNINGEXPECTATIONS = AttributesEnum.LearningExpectations.index();
    public static final int IMPACTONJOB = AttributesEnum.ImpactOnJob.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int NEXTAPPROVER = AttributesEnum.NextApprover.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int PREVIOUSAPPROVER = AttributesEnum.PreviousApprover.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int DEPTMANAGEREMAILADDR = AttributesEnum.DeptManagerEmailAddr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxsshrJmrFormEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.eo.XxsshrJmrFormEO");
    }

    /**
     * Gets the attribute value for JmrFormId, using the alias name JmrFormId.
     * @return the value of JmrFormId
     */
    public BigDecimal getJmrFormId() {
        return (BigDecimal) getAttributeInternal(JMRFORMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JmrFormId.
     * @param value value to set the JmrFormId
     */
    public void setJmrFormId(BigDecimal value) {
        setAttributeInternal(JMRFORMID, value);
    }

    /**
     * Gets the attribute value for JmrFormNo, using the alias name JmrFormNo.
     * @return the value of JmrFormNo
     */
    public String getJmrFormNo() {
        return (String) getAttributeInternal(JMRFORMNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for JmrFormNo.
     * @param value value to set the JmrFormNo
     */
    public void setJmrFormNo(String value) {
        setAttributeInternal(JMRFORMNO, value);
    }

    /**
     * Gets the attribute value for PersonId, using the alias name PersonId.
     * @return the value of PersonId
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonId.
     * @param value value to set the PersonId
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for BusinessUnitId, using the alias name BusinessUnitId.
     * @return the value of BusinessUnitId
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessUnitId.
     * @param value value to set the BusinessUnitId
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for TransactionDate, using the alias name TransactionDate.
     * @return the value of TransactionDate
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionDate.
     * @param value value to set the TransactionDate
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for Nominator, using the alias name Nominator.
     * @return the value of Nominator
     */
    public String getNominator() {
        return (String) getAttributeInternal(NOMINATOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Nominator.
     * @param value value to set the Nominator
     */
    public void setNominator(String value) {
        setAttributeInternal(NOMINATOR, value);
    }

    /**
     * Gets the attribute value for EmployeeName, using the alias name EmployeeName.
     * @return the value of EmployeeName
     */
    public String getEmployeeName() {
        return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeName.
     * @param value value to set the EmployeeName
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for Cadre, using the alias name Cadre.
     * @return the value of Cadre
     */
    public String getCadre() {
        return (String) getAttributeInternal(CADRE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cadre.
     * @param value value to set the Cadre
     */
    public void setCadre(String value) {
        setAttributeInternal(CADRE, value);
    }

    /**
     * Gets the attribute value for Position, using the alias name Position.
     * @return the value of Position
     */
    public String getPosition() {
        return (String) getAttributeInternal(POSITION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Position.
     * @param value value to set the Position
     */
    public void setPosition(String value) {
        setAttributeInternal(POSITION, value);
    }

    /**
     * Gets the attribute value for DepartmentName, using the alias name DepartmentName.
     * @return the value of DepartmentName
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentName.
     * @param value value to set the DepartmentName
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for LineManager, using the alias name LineManager.
     * @return the value of LineManager
     */
    public String getLineManager() {
        return (String) getAttributeInternal(LINEMANAGER);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineManager.
     * @param value value to set the LineManager
     */
    public void setLineManager(String value) {
        setAttributeInternal(LINEMANAGER, value);
    }

    /**
     * Gets the attribute value for ApprovalStatus, using the alias name ApprovalStatus.
     * @return the value of ApprovalStatus
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalStatus.
     * @param value value to set the ApprovalStatus
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for MobilityDepartment, using the alias name MobilityDepartment.
     * @return the value of MobilityDepartment
     */
    public String getMobilityDepartment() {
        return (String) getAttributeInternal(MOBILITYDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilityDepartment.
     * @param value value to set the MobilityDepartment
     */
    public void setMobilityDepartment(String value) {
        setAttributeInternal(MOBILITYDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for MobilityDeptManager, using the alias name MobilityDeptManager.
     * @return the value of MobilityDeptManager
     */
    public String getMobilityDeptManager() {
        return (String) getAttributeInternal(MOBILITYDEPTMANAGER);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilityDeptManager.
     * @param value value to set the MobilityDeptManager
     */
    public void setMobilityDeptManager(String value) {
        setAttributeInternal(MOBILITYDEPTMANAGER, value);
    }

    /**
     * Gets the attribute value for MobilityType, using the alias name MobilityType.
     * @return the value of MobilityType
     */
    public String getMobilityType() {
        return (String) getAttributeInternal(MOBILITYTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobilityType.
     * @param value value to set the MobilityType
     */
    public void setMobilityType(String value) {
        setAttributeInternal(MOBILITYTYPE, value);
    }

    /**
     * Gets the attribute value for Duration, using the alias name Duration.
     * @return the value of Duration
     */
    public String getDuration() {
        return (String) getAttributeInternal(DURATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Duration.
     * @param value value to set the Duration
     */
    public void setDuration(String value) {
        setAttributeInternal(DURATION, value);
    }

    /**
     * Gets the attribute value for ProposedStartDate, using the alias name ProposedStartDate.
     * @return the value of ProposedStartDate
     */
    public Timestamp getProposedStartDate() {
        return (Timestamp) getAttributeInternal(PROPOSEDSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProposedStartDate.
     * @param value value to set the ProposedStartDate
     */
    public void setProposedStartDate(Timestamp value) {
        setAttributeInternal(PROPOSEDSTARTDATE, value);
    }

    /**
     * Gets the attribute value for ProposedEndDate, using the alias name ProposedEndDate.
     * @return the value of ProposedEndDate
     */
    public Timestamp getProposedEndDate() {
        return (Timestamp) getAttributeInternal(PROPOSEDENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProposedEndDate.
     * @param value value to set the ProposedEndDate
     */
    public void setProposedEndDate(Timestamp value) {
        setAttributeInternal(PROPOSEDENDDATE, value);
    }

    /**
     * Gets the attribute value for LearningExpectations, using the alias name LearningExpectations.
     * @return the value of LearningExpectations
     */
    public String getLearningExpectations() {
        return (String) getAttributeInternal(LEARNINGEXPECTATIONS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LearningExpectations.
     * @param value value to set the LearningExpectations
     */
    public void setLearningExpectations(String value) {
        setAttributeInternal(LEARNINGEXPECTATIONS, value);
    }

    /**
     * Gets the attribute value for ImpactOnJob, using the alias name ImpactOnJob.
     * @return the value of ImpactOnJob
     */
    public String getImpactOnJob() {
        return (String) getAttributeInternal(IMPACTONJOB);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpactOnJob.
     * @param value value to set the ImpactOnJob
     */
    public void setImpactOnJob(String value) {
        setAttributeInternal(IMPACTONJOB, value);
    }

    /**
     * Gets the attribute value for Comments, using the alias name Comments.
     * @return the value of Comments
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Comments.
     * @param value value to set the Comments
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for NextApprover, using the alias name NextApprover.
     * @return the value of NextApprover
     */
    public String getNextApprover() {
        return (String) getAttributeInternal(NEXTAPPROVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextApprover.
     * @param value value to set the NextApprover
     */
    public void setNextApprover(String value) {
        setAttributeInternal(NEXTAPPROVER, value);
    }

    /**
     * Gets the attribute value for ApproverComments, using the alias name ApproverComments.
     * @return the value of ApproverComments
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApproverComments.
     * @param value value to set the ApproverComments
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for PreviousApprover, using the alias name PreviousApprover.
     * @return the value of PreviousApprover
     */
    public String getPreviousApprover() {
        return (String) getAttributeInternal(PREVIOUSAPPROVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousApprover.
     * @param value value to set the PreviousApprover
     */
    public void setPreviousApprover(String value) {
        setAttributeInternal(PREVIOUSAPPROVER, value);
    }

    /**
     * Gets the attribute value for PayrollBatchName, using the alias name PayrollBatchName.
     * @return the value of PayrollBatchName
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PayrollBatchName.
     * @param value value to set the PayrollBatchName
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for SoaFlowid, using the alias name SoaFlowid.
     * @return the value of SoaFlowid
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoaFlowid.
     * @param value value to set the SoaFlowid
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for ErrorMsg, using the alias name ErrorMsg.
     * @return the value of ErrorMsg
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorMsg.
     * @param value value to set the ErrorMsg
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the value of LastUpdateLogin
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for DeptManagerEmailAddr, using the alias name DeptManagerEmailAddr.
     * @return the value of DeptManagerEmailAddr
     */
    public String getDeptManagerEmailAddr() {
        return (String) getAttributeInternal(DEPTMANAGEREMAILADDR);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeptManagerEmailAddr.
     * @param value value to set the DeptManagerEmailAddr
     */
    public void setDeptManagerEmailAddr(String value) {
        setAttributeInternal(DEPTMANAGEREMAILADDR, value);
    }

    /**
     * @param jmrFormId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal jmrFormId) {
        return new Key(new Object[] { jmrFormId });
    }

}

