package model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.eo.XxsshrJmrFormEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 30 14:45:31 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxsshrJmrFormVORowImpl extends ViewRowImpl {


    public static final int ENTITY_XXSSHRJMRFORMEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        JmrFormId,
        JmrFormNo,
        PersonId,
        BusinessUnitId,
        TransactionDate,
        Nominator,
        EmployeeName,
        Cadre,
        Position,
        DepartmentName,
        LineManager,
        ApprovalStatus,
        MobilityDepartment,
        MobilityDeptManager,
        MobilityType,
        Duration,
        ProposedStartDate,
        ProposedEndDate,
        LearningExpectations,
        ImpactOnJob,
        Comments,
        NextApprover,
        ApproverComments,
        PreviousApprover,
        PayrollBatchName,
        SoaFlowid,
        ErrorMsg,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        LastUpdateLogin,
        DeptManagerEmailAddr,
        Number_Trns,
        Group_Trns,
        Email_Trns,
        Trans_AssignmentType,
        Position_Trns,
        NominatorCount,
        Nomnie_Mail,
        Employee_View_ROVO,
        DurationROVO,
        NominatorEmployee_ROVO,
        MobilityTypeROVO,
        MobilityDeptManagers_ROVO,
        XXPER_MANAGER_HRCY_R1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int JMRFORMID = AttributesEnum.JmrFormId.index();
    public static final int JMRFORMNO = AttributesEnum.JmrFormNo.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int BUSINESSUNITID = AttributesEnum.BusinessUnitId.index();
    public static final int TRANSACTIONDATE = AttributesEnum.TransactionDate.index();
    public static final int NOMINATOR = AttributesEnum.Nominator.index();
    public static final int EMPLOYEENAME = AttributesEnum.EmployeeName.index();
    public static final int CADRE = AttributesEnum.Cadre.index();
    public static final int POSITION = AttributesEnum.Position.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int LINEMANAGER = AttributesEnum.LineManager.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int MOBILITYDEPARTMENT = AttributesEnum.MobilityDepartment.index();
    public static final int MOBILITYDEPTMANAGER = AttributesEnum.MobilityDeptManager.index();
    public static final int MOBILITYTYPE = AttributesEnum.MobilityType.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int PROPOSEDSTARTDATE = AttributesEnum.ProposedStartDate.index();
    public static final int PROPOSEDENDDATE = AttributesEnum.ProposedEndDate.index();
    public static final int LEARNINGEXPECTATIONS = AttributesEnum.LearningExpectations.index();
    public static final int IMPACTONJOB = AttributesEnum.ImpactOnJob.index();
    public static final int COMMENTS = AttributesEnum.Comments.index();
    public static final int NEXTAPPROVER = AttributesEnum.NextApprover.index();
    public static final int APPROVERCOMMENTS = AttributesEnum.ApproverComments.index();
    public static final int PREVIOUSAPPROVER = AttributesEnum.PreviousApprover.index();
    public static final int PAYROLLBATCHNAME = AttributesEnum.PayrollBatchName.index();
    public static final int SOAFLOWID = AttributesEnum.SoaFlowid.index();
    public static final int ERRORMSG = AttributesEnum.ErrorMsg.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int DEPTMANAGEREMAILADDR = AttributesEnum.DeptManagerEmailAddr.index();
    public static final int NUMBER_TRNS = AttributesEnum.Number_Trns.index();
    public static final int GROUP_TRNS = AttributesEnum.Group_Trns.index();
    public static final int EMAIL_TRNS = AttributesEnum.Email_Trns.index();
    public static final int TRANS_ASSIGNMENTTYPE = AttributesEnum.Trans_AssignmentType.index();
    public static final int POSITION_TRNS = AttributesEnum.Position_Trns.index();
    public static final int NOMINATORCOUNT = AttributesEnum.NominatorCount.index();
    public static final int NOMNIE_MAIL = AttributesEnum.Nomnie_Mail.index();
    public static final int EMPLOYEE_VIEW_ROVO = AttributesEnum.Employee_View_ROVO.index();
    public static final int DURATIONROVO = AttributesEnum.DurationROVO.index();
    public static final int NOMINATOREMPLOYEE_ROVO = AttributesEnum.NominatorEmployee_ROVO.index();
    public static final int MOBILITYTYPEROVO = AttributesEnum.MobilityTypeROVO.index();
    public static final int MOBILITYDEPTMANAGERS_ROVO = AttributesEnum.MobilityDeptManagers_ROVO.index();
    public static final int XXPER_MANAGER_HRCY_R1 = AttributesEnum.XXPER_MANAGER_HRCY_R1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxsshrJmrFormVORowImpl() {
    }

    /**
     * Gets XxsshrJmrFormEO entity object.
     * @return the XxsshrJmrFormEO
     */
    public XxsshrJmrFormEOImpl getXxsshrJmrFormEO() {
        return (XxsshrJmrFormEOImpl) getEntity(ENTITY_XXSSHRJMRFORMEO);
    }

    /**
     * Gets the attribute value for JMR_FORM_ID using the alias name JmrFormId.
     * @return the JMR_FORM_ID
     */
    public BigDecimal getJmrFormId() {
        return (BigDecimal) getAttributeInternal(JMRFORMID);
    }

    /**
     * Sets <code>value</code> as attribute value for JMR_FORM_ID using the alias name JmrFormId.
     * @param value value to set the JMR_FORM_ID
     */
    public void setJmrFormId(BigDecimal value) {
        setAttributeInternal(JMRFORMID, value);
    }

    /**
     * Gets the attribute value for JMR_FORM_NO using the alias name JmrFormNo.
     * @return the JMR_FORM_NO
     */
    public String getJmrFormNo() {
        return (String) getAttributeInternal(JMRFORMNO);
    }

    /**
     * Sets <code>value</code> as attribute value for JMR_FORM_NO using the alias name JmrFormNo.
     * @param value value to set the JMR_FORM_NO
     */
    public void setJmrFormNo(String value) {
        setAttributeInternal(JMRFORMNO, value);
    }

    /**
     * Gets the attribute value for PERSON_ID using the alias name PersonId.
     * @return the PERSON_ID
     */
    public BigDecimal getPersonId() {
        return (BigDecimal) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for PERSON_ID using the alias name PersonId.
     * @param value value to set the PERSON_ID
     */
    public void setPersonId(BigDecimal value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @return the BUSINESS_UNIT_ID
     */
    public BigDecimal getBusinessUnitId() {
        return (BigDecimal) getAttributeInternal(BUSINESSUNITID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUSINESS_UNIT_ID using the alias name BusinessUnitId.
     * @param value value to set the BUSINESS_UNIT_ID
     */
    public void setBusinessUnitId(BigDecimal value) {
        setAttributeInternal(BUSINESSUNITID, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @return the TRANSACTION_DATE
     */
    public Timestamp getTransactionDate() {
        return (Timestamp) getAttributeInternal(TRANSACTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_DATE using the alias name TransactionDate.
     * @param value value to set the TRANSACTION_DATE
     */
    public void setTransactionDate(Timestamp value) {
        setAttributeInternal(TRANSACTIONDATE, value);
    }

    /**
     * Gets the attribute value for NOMINATOR using the alias name Nominator.
     * @return the NOMINATOR
     */
    public String getNominator() {
        return (String) getAttributeInternal(NOMINATOR);
    }

    /**
     * Sets <code>value</code> as attribute value for NOMINATOR using the alias name Nominator.
     * @param value value to set the NOMINATOR
     */
    public void setNominator(String value) {
        setAttributeInternal(NOMINATOR, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @return the EMPLOYEE_NAME
     */
    public String getEmployeeName() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("DisplayName")== null ? " " : orgRows[0].getAttribute("DisplayName").toString();
                System.out.println("name ------- " + name);
            }
            return name;
        } else {

            return (String) getAttributeInternal(EMPLOYEENAME);
        }
        // return (String) getAttributeInternal(EMPLOYEENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_NAME using the alias name EmployeeName.
     * @param value value to set the EMPLOYEE_NAME
     */
    public void setEmployeeName(String value) {
        setAttributeInternal(EMPLOYEENAME, value);
    }

    /**
     * Gets the attribute value for CADRE using the alias name Cadre.
     * @return the CADRE
     */
    public String getCadre() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("Cadre") == null ? " " : orgRows[0].getAttribute("Cadre").toString();
            }
            return name;
        } else {

            return (String) getAttributeInternal(CADRE);
        }
        // return (String) getAttributeInternal(CADRE);
    }

    /**
     * Sets <code>value</code> as attribute value for CADRE using the alias name Cadre.
     * @param value value to set the CADRE
     */
    public void setCadre(String value) {
        setAttributeInternal(CADRE, value);
    }

    /**
     * Gets the attribute value for POSITION using the alias name Position.
     * @return the POSITION
     */
    public String getPosition() {
        return (String) getAttributeInternal(POSITION);
    }

    /**
     * Sets <code>value</code> as attribute value for POSITION using the alias name Position.
     * @param value value to set the POSITION
     */
    public void setPosition(String value) {
        setAttributeInternal(POSITION, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @return the DEPARTMENT_NAME
     */
    public String getDepartmentName() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("DepartmentName") == null ? " " : orgRows[0].getAttribute("DepartmentName").toString();
            }
            System.out.println("Dept name ---------- " + name);
            return name;
        } else {

            return (String) getAttributeInternal(DEPARTMENTNAME);
        }
        //return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @param value value to set the DEPARTMENT_NAME
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for LINE_MANAGER using the alias name LineManager.
     * @return the LINE_MANAGER
     */
    public String getLineManager() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            System.out.println("orgRows.length ----- " + orgRows.length);
            if (orgRows.length > 0) {
                if (orgRows[0].getAttribute("SupervisorName") != null) {
                    name = orgRows[0].getAttribute("SupervisorName") == null ? " " : orgRows[0].getAttribute("SupervisorName").toString();
                } else {
                    name = "";
                }

            }
            System.out.println("Supervisor name ---------- " + name);
            return name;
        } else {

            return (String) getAttributeInternal(LINEMANAGER);
        }
        //return (String) getAttributeInternal(LINEMANAGER);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_MANAGER using the alias name LineManager.
     * @param value value to set the LINE_MANAGER
     */
    public void setLineManager(String value) {
        setAttributeInternal(LINEMANAGER, value);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for MOBILITY_DEPARTMENT using the alias name MobilityDepartment.
     * @return the MOBILITY_DEPARTMENT
     */
    public String getMobilityDepartment() {
        return (String) getAttributeInternal(MOBILITYDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILITY_DEPARTMENT using the alias name MobilityDepartment.
     * @param value value to set the MOBILITY_DEPARTMENT
     */
    public void setMobilityDepartment(String value) {
        setAttributeInternal(MOBILITYDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for MOBILITY_DEPT_MANAGER using the alias name MobilityDeptManager.
     * @return the MOBILITY_DEPT_MANAGER
     */
    public String getMobilityDeptManager() {
        return (String) getAttributeInternal(MOBILITYDEPTMANAGER);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILITY_DEPT_MANAGER using the alias name MobilityDeptManager.
     * @param value value to set the MOBILITY_DEPT_MANAGER
     */
    public void setMobilityDeptManager(String value) {
        setAttributeInternal(MOBILITYDEPTMANAGER, value);
    }

    /**
     * Gets the attribute value for MOBILITY_TYPE using the alias name MobilityType.
     * @return the MOBILITY_TYPE
     */
    public String getMobilityType() {
        return (String) getAttributeInternal(MOBILITYTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MOBILITY_TYPE using the alias name MobilityType.
     * @param value value to set the MOBILITY_TYPE
     */
    public void setMobilityType(String value) {
        setAttributeInternal(MOBILITYTYPE, value);
    }

    /**
     * Gets the attribute value for DURATION using the alias name Duration.
     * @return the DURATION
     */
    public String getDuration() {
        return (String) getAttributeInternal(DURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DURATION using the alias name Duration.
     * @param value value to set the DURATION
     */
    public void setDuration(String value) {
        setAttributeInternal(DURATION, value);
    }

    /**
     * Gets the attribute value for PROPOSED_START_DATE using the alias name ProposedStartDate.
     * @return the PROPOSED_START_DATE
     */
    public Timestamp getProposedStartDate() {
        return (Timestamp) getAttributeInternal(PROPOSEDSTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSED_START_DATE using the alias name ProposedStartDate.
     * @param value value to set the PROPOSED_START_DATE
     */
    public void setProposedStartDate(Timestamp value) {
        setAttributeInternal(PROPOSEDSTARTDATE, value);
    }

    /**
     * Gets the attribute value for PROPOSED_END_DATE using the alias name ProposedEndDate.
     * @return the PROPOSED_END_DATE
     */
    public Timestamp getProposedEndDate() {
        return (Timestamp) getAttributeInternal(PROPOSEDENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSED_END_DATE using the alias name ProposedEndDate.
     * @param value value to set the PROPOSED_END_DATE
     */
    public void setProposedEndDate(Timestamp value) {
        setAttributeInternal(PROPOSEDENDDATE, value);
    }

    /**
     * Gets the attribute value for LEARNING_EXPECTATIONS using the alias name LearningExpectations.
     * @return the LEARNING_EXPECTATIONS
     */
    public String getLearningExpectations() {
        return (String) getAttributeInternal(LEARNINGEXPECTATIONS);
    }

    /**
     * Sets <code>value</code> as attribute value for LEARNING_EXPECTATIONS using the alias name LearningExpectations.
     * @param value value to set the LEARNING_EXPECTATIONS
     */
    public void setLearningExpectations(String value) {
        setAttributeInternal(LEARNINGEXPECTATIONS, value);
    }

    /**
     * Gets the attribute value for IMPACT_ON_JOB using the alias name ImpactOnJob.
     * @return the IMPACT_ON_JOB
     */
    public String getImpactOnJob() {
        return (String) getAttributeInternal(IMPACTONJOB);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPACT_ON_JOB using the alias name ImpactOnJob.
     * @param value value to set the IMPACT_ON_JOB
     */
    public void setImpactOnJob(String value) {
        setAttributeInternal(IMPACTONJOB, value);
    }

    /**
     * Gets the attribute value for COMMENTS using the alias name Comments.
     * @return the COMMENTS
     */
    public String getComments() {
        return (String) getAttributeInternal(COMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMENTS using the alias name Comments.
     * @param value value to set the COMMENTS
     */
    public void setComments(String value) {
        setAttributeInternal(COMMENTS, value);
    }

    /**
     * Gets the attribute value for NEXT_APPROVER using the alias name NextApprover.
     * @return the NEXT_APPROVER
     */
    public String getNextApprover() {
        return (String) getAttributeInternal(NEXTAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for NEXT_APPROVER using the alias name NextApprover.
     * @param value value to set the NEXT_APPROVER
     */
    public void setNextApprover(String value) {
        setAttributeInternal(NEXTAPPROVER, value);
    }

    /**
     * Gets the attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @return the APPROVER_COMMENTS
     */
    public String getApproverComments() {
        return (String) getAttributeInternal(APPROVERCOMMENTS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVER_COMMENTS using the alias name ApproverComments.
     * @param value value to set the APPROVER_COMMENTS
     */
    public void setApproverComments(String value) {
        setAttributeInternal(APPROVERCOMMENTS, value);
    }

    /**
     * Gets the attribute value for PREVIOUS_APPROVER using the alias name PreviousApprover.
     * @return the PREVIOUS_APPROVER
     */
    public String getPreviousApprover() {
        return (String) getAttributeInternal(PREVIOUSAPPROVER);
    }

    /**
     * Sets <code>value</code> as attribute value for PREVIOUS_APPROVER using the alias name PreviousApprover.
     * @param value value to set the PREVIOUS_APPROVER
     */
    public void setPreviousApprover(String value) {
        setAttributeInternal(PREVIOUSAPPROVER, value);
    }

    /**
     * Gets the attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @return the PAYROLL_BATCH_NAME
     */
    public String getPayrollBatchName() {
        return (String) getAttributeInternal(PAYROLLBATCHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYROLL_BATCH_NAME using the alias name PayrollBatchName.
     * @param value value to set the PAYROLL_BATCH_NAME
     */
    public void setPayrollBatchName(String value) {
        setAttributeInternal(PAYROLLBATCHNAME, value);
    }

    /**
     * Gets the attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @return the SOA_FLOWID
     */
    public BigDecimal getSoaFlowid() {
        return (BigDecimal) getAttributeInternal(SOAFLOWID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOA_FLOWID using the alias name SoaFlowid.
     * @param value value to set the SOA_FLOWID
     */
    public void setSoaFlowid(BigDecimal value) {
        setAttributeInternal(SOAFLOWID, value);
    }

    /**
     * Gets the attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @return the ERROR_MSG
     */
    public ClobDomain getErrorMsg() {
        return (ClobDomain) getAttributeInternal(ERRORMSG);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MSG using the alias name ErrorMsg.
     * @param value value to set the ERROR_MSG
     */
    public void setErrorMsg(ClobDomain value) {
        setAttributeInternal(ERRORMSG, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for DEPT_MANAGER_EMAIL_ADDR using the alias name DeptManagerEmailAddr.
     * @return the DEPT_MANAGER_EMAIL_ADDR
     */
    public String getDeptManagerEmailAddr() {
        return (String) getAttributeInternal(DEPTMANAGEREMAILADDR);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT_MANAGER_EMAIL_ADDR using the alias name DeptManagerEmailAddr.
     * @param value value to set the DEPT_MANAGER_EMAIL_ADDR
     */
    public void setDeptManagerEmailAddr(String value) {
        setAttributeInternal(DEPTMANAGEREMAILADDR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Number_Trns.
     * @return the Number_Trns
     */
    public String getNumber_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PersonNumber") == null ?" " : orgRows[0].getAttribute("PersonNumber").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(NUMBER_TRNS);

        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Number_Trns.
     * @param value value to set the  Number_Trns
     */
    public void setNumber_Trns(String value) {
        setAttributeInternal(NUMBER_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Group_Trns.
     * @return the Group_Trns
     */
    public String getGroup_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("BusinessUnitName") == null ? " " : orgRows[0].getAttribute("BusinessUnitName").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(GROUP_TRNS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Group_Trns.
     * @param value value to set the  Group_Trns
     */
    public void setGroup_Trns(String value) {
        setAttributeInternal(GROUP_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email_Trns.
     * @return the Email_Trns
     */
    public String getEmail_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("EmailAddress")== null ? " " : orgRows[0].getAttribute("EmailAddress").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(EMAIL_TRNS);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email_Trns.
     * @param value value to set the  Email_Trns
     */
    public void setEmail_Trns(String value) {
        setAttributeInternal(EMAIL_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Trans_AssignmentType.
     * @return the Trans_AssignmentType
     */
    public String getTrans_AssignmentType() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PersonType") == null ? " " : orgRows[0].getAttribute("PersonType").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(TRANS_ASSIGNMENTTYPE);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Trans_AssignmentType.
     * @param value value to set the  Trans_AssignmentType
     */
    public void setTrans_AssignmentType(String value) {
        setAttributeInternal(TRANS_ASSIGNMENTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Position_Trns.
     * @return the Position_Trns
     */
    public String getPosition_Trns() {
        BigDecimal type = null;
        String name = null;
        if (getPersonId() != null) {
            type = (BigDecimal) getPersonId();
            Row[] orgRows;
            orgRows = getEmployee_View_ROVO().getFilteredRows("PersonId", type);
            if (orgRows.length > 0) {
                name = orgRows[0].getAttribute("PositionName")== null ?" " : orgRows[0].getAttribute("PositionName").toString();
            }
            return name;
        } else {
            return (String) getAttributeInternal(POSITION_TRNS);
        }
       // return (String) getAttributeInternal(POSITION_TRNS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Position_Trns.
     * @param value value to set the  Position_Trns
     */
    public void setPosition_Trns(String value) {
        setAttributeInternal(POSITION_TRNS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NominatorCount.
     * @return the NominatorCount
     */
    public String getNominatorCount() {
        return (String) getAttributeInternal(NOMINATORCOUNT);
    }

    /**
     * Gets the attribute value for the calculated attribute Nomnie_Mail.
     * @return the Nomnie_Mail
     */
    public String getNomnie_Mail() {
        return (String) getAttributeInternal(NOMNIE_MAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Nomnie_Mail.
     * @param value value to set the  Nomnie_Mail
     */
    public void setNomnie_Mail(String value) {
        setAttributeInternal(NOMNIE_MAIL, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Employee_View_ROVO.
     */
    public RowSet getEmployee_View_ROVO() {
        return (RowSet) getAttributeInternal(EMPLOYEE_VIEW_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DurationROVO.
     */
    public RowSet getDurationROVO() {
        return (RowSet) getAttributeInternal(DURATIONROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> NominatorEmployee_ROVO.
     */
    public RowSet getNominatorEmployee_ROVO() {
        return (RowSet) getAttributeInternal(NOMINATOREMPLOYEE_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MobilityTypeROVO.
     */
    public RowSet getMobilityTypeROVO() {
        return (RowSet) getAttributeInternal(MOBILITYTYPEROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MobilityDeptManagers_ROVO.
     */
    public RowSet getMobilityDeptManagers_ROVO() {
        return (RowSet) getAttributeInternal(MOBILITYDEPTMANAGERS_ROVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> XXPER_MANAGER_HRCY_R1.
     */
    public RowSet getXXPER_MANAGER_HRCY_R1() {
        return (RowSet) getAttributeInternal(XXPER_MANAGER_HRCY_R1);
    }
}

